services:
  frontend:
    image: xxroloxx/ttt-frontend:latest
    build:
      context: ./tic-tac-toe-frontend/
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: tic-tac-toe_frontend_prod
  backend:
    image: xxroloxx/ttt-backend:latest
    container_name: tic-tac-toe_backend_prod
    build: ./tic-tac-toe-backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    working_dir: /app
    networks:
      - backend
  database:
    image: postgres:latest
    container_name: tic-tac-toe_db_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  postgres-data-dev:
  pgadmin-data:
