services:
  # frontend:
  #   build: ./tic-tac-toe-frontend/
  #   ports:
  #     - "3000:3000"
  # backend:
  #   build: ./tic-tac-toe-backend/
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - backend
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  postgres-data:
