#!/bin/env bash

#This script is used to build the frontend of the application with address of the backend generated by the terraform script
#cd aws
#BACKEND_ADDRESS=$(terraform output -json | jq -r '.fargate_backend_public_ip.value')
#cd ..

# Get the ENI ID
#
# GET TASK_ID and CLUSTER_NAME From environment
#



echo "Formatting TASK_ID (getting all characters after last /)"
echo "TASK_ID: $TASK_ID"

# JSON_ARN=$(aws ecs list-tasks --cluster ecs-cluster --family tic-tac-toe-backend)
#
# ARN=$(echo $JSON_ARN | jq -r '.taskArns[0]')
#
# TASK_ID=$(echo $ARN | awk -F'/' '{print $NF}')
#
# echo "TASK_ID  : $TASK_ID"
# echo "CLUSTER_NAME : $CLUSTER_NAME"
#
# ENI=$(aws ecs describe-tasks --cluster "$CLUSTER_NAME" --tasks "$TASK_ID" --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value[0]')
#
# echo "ENI: $ENI"

IP=$(aws ec2 describe-network-interfaces --network-interface-ids "[]"\
  --query 'NetworkInterfaces[0].Association.PublicIp' --output text)

echo "IP: $IP"

BACKEND_ADDRESS=$IP

# Elastic beanstalk address
#BACKEND_ADDRESS=ttt-xxroloxx.us-east-1.elasticbeanstalk.com

echo "Building the frontend with the backend address: $BACKEND_ADDRESS"

sudo docker build -t xxroloxx/ttt-frontend:latest --build-arg VITE_API_URL=http://$BACKEND_ADDRESS:8080 ../../lab-1-TicTacToe/tic-tac-toe-frontend/

echo "Pushing the frontend image to the registry"

sudo docker push xxroloxx/ttt-frontend:latest

